//! The crypt(3) hashes against `vectors/unix_crypt.vec`: libxcrypt's
//! known-answer table (generated by Passlib, an independent
//! implementation) with the system libcrypt agreeing. Offline.

use std::collections::HashMap;

use allcrypt::kdf::unix_crypt::{crypt, verify};

/// A C string literal's bytes: `\xHH`, octal `\NNN`, and the usual
/// single-character escapes. The settings and expected hashes are
/// written this way because a few carry bytes outside ASCII.
fn decode_c(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < b.len() {
        if b[i] != b'\\' {
            out.push(b[i]);
            i += 1;
            continue;
        }
        match b[i + 1] {
            b'x' => {
                out.push(u8::from_str_radix(&s[i + 2..i + 4], 16).unwrap());
                i += 4;
            }
            d @ b'0'..=b'7' => {
                let mut j = i + 1;
                while j < b.len() && j < i + 4 && (b'0'..=b'7').contains(&b[j]) {
                    j += 1;
                }
                out.push(u8::from_str_radix(&s[i + 1..j], 8).unwrap());
                i = j;
                let _ = d;
            }
            b'n' => { out.push(b'\n'); i += 2; }
            b't' => { out.push(b'\t'); i += 2; }
            b'r' => { out.push(b'\r'); i += 2; }
            other => { out.push(other); i += 2; }
        }
    }
    out
}

fn unhex(s: &str) -> Vec<u8> {
    if s == "-" {
        return Vec::new();
    }
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

#[test]
fn test_unix_crypt_vectors() {
    let text = include_str!("../vectors/unix_crypt.vec");
    let mut counts: HashMap<String, usize> = HashMap::new();
    for line in text.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let mut words = line.split(' ');
        let method = words.next().unwrap().to_string();
        let mut f = HashMap::new();
        for w in words {
            let (k, v) = w.split_once('=').unwrap();
            f.insert(k, v);
        }
        let setting = String::from_utf8(decode_c(f["setting"])).unwrap();
        let phrase = unhex(f["phrase"]);
        let expected = String::from_utf8(decode_c(f["expected"])).unwrap();

        let got = crypt(&phrase, &setting)
            .unwrap_or_else(|e| panic!("{method}: {line}\n  error: {e}"));
        assert_eq!(got, expected, "{method}: {line}");
        // verify() is the constant-time comparison a caller uses.
        assert!(verify(&phrase, &expected), "verify {method}: {line}");
        *counts.entry(method).or_default() += 1;
    }
    // A parser that found nothing would pass every assertion above.
    for method in ["descrypt", "bsdicrypt", "bigcrypt", "md5crypt", "bcrypt", "nt",
                   "sha1crypt", "sha256crypt", "sha512crypt", "sunmd5"] {
        assert!(counts.get(method).copied().unwrap_or(0) >= 100,
                "too few {method} rows: {:?}", counts.get(method));
    }
}

/// A password that is one byte off must not verify - the vectors are all
/// positive, so the negative case needs its own check.
#[test]
fn test_a_wrong_password_does_not_verify() {
    // Passwords that differ within the first eight bytes, since DES crypt
    // ignores anything past them.
    for setting in ["ab", "_J9..rasm", "$1$abcdefgh", "$5$saltstring", "$6$saltstring",
                    "$2b$05$CCCCCCCCCCCCCCCCCCCCC.", "$sha1$1000$abcdefgh"] {
        let right = crypt(b"hunter2", setting).unwrap();
        assert!(verify(b"hunter2", &right), "{setting}");
        assert!(!verify(b"hunter3", &right), "{setting}");
        assert!(!verify(b"Hunter2", &right), "{setting}");
    }
}
