//! Real GOST certificates, from real servers, checked offline.
//!
//! **These are the only certificates in this repository that this
//! library did not produce.** Everything else the verifier is tested
//! against was generated by `x509::builder` or by OpenSSL, and the ways
//! those get written are the ways we already thought of. These three
//! came off the wire from CryptoPro's public GOST TLS endpoints, saved
//! by `scripts/fetch_chain.py`, and each one found something:
//!
//!   * `tlsgost-256` and `tlsgost-512` were **refused outright** by a
//!     check that read `BMPString` bytes as if they were a null-prefix
//!     attack. Every ASCII character in a `BMPString` is `00 xx`, and
//!     `BMPString` is a common encoding for Cyrillic - so the check
//!     refused exactly the certificates this library exists to read.
//!     See `x509::Attribute::text`.
//!   * all three carry names this library had never had to decode: a
//!     Cyrillic organisation, a street address, and OIDs from Russia's
//!     own arc (`1.2.643.100.1`, an OGRN; `1.2.643.100.4`, an INN)
//!     that no other test here uses.
//!
//! **The strongest check is the last one.** RFC 9215 section 4.3 writes
//! a GOST public key as an OCTET STRING inside a BIT STRING, with the
//! coordinates **little endian**. Nothing about that is visible from a
//! certificate we generated, because our reader and our writer agree.
//! Here the bytes came from somebody else's CA, so reading them the
//! wrong way round gives a pair of numbers that are not a point on the
//! curve at all - and the curve equation says so. That is a real
//! independent check of the encoding, and there was no other one.
//!
//! What these cannot check: the signatures. All three servers sent the
//! **leaf alone** - no issuer, which RFC 8446 4.4.2 permits - so there
//! is no key here to verify them with. Said out loud rather than left
//! as a gap nobody counted.
//!
//! Refetching: `python3 scripts/fetch_chain.py <host>`. Nothing in this
//! file reaches the network, and nothing may: every test here is
//! offline and `pytests/conftest.py` enforces it.

use allcrypt::bignum::BigUint;
use allcrypt::ec::curves;
use allcrypt::x509::{Certificate, GeneralName, PublicKey};

struct Live {
    host: &'static str,
    der: &'static [u8],
    /// What the key should come out as, and which generation.
    curve: &'static str,
    legacy: bool,
    /// The key's parameter-set OID, which is **not** determined by
    /// `curve`. See `test_the_parameter_sets_are_not_all_canonical`.
    param_set: &'static str,
    /// A name from the subject that is not ASCII, or `None`.
    cyrillic: Option<&'static str>,
}

const LIVE: &[Live] = &[
    Live {
        host: "tlsgost-256.cryptopro.ru",
        der: include_bytes!("../vectors/live/tlsgost-256.cryptopro.ru-0.der"),
        curve: "gost256-a",
        legacy: false,
        param_set: "1.2.643.2.2.36.0",
        cyrillic: None,
    },
    Live {
        host: "tlsgost-512.cryptopro.ru",
        der: include_bytes!("../vectors/live/tlsgost-512.cryptopro.ru-0.der"),
        curve: "gost512-a",
        legacy: false,
        param_set: "1.2.643.7.1.2.1.2.1",
        cyrillic: None,
    },
    Live {
        host: "www.cryptopro.ru",
        der: include_bytes!("../vectors/live/www.cryptopro.ru-0.der"),
        curve: "gost256-a",
        legacy: false,
        param_set: "1.2.643.2.2.36.0",
        // The subject's CN is Cyrillic, which is the half of these
        // certificates that no generated one has.
        cyrillic: Some("Веб-сервер"),
    },
];

/// They parse at all, which two of them did not.
#[test]
fn test_every_live_certificate_parses() {
    for live in LIVE {
        Certificate::parse(live.der)
            .unwrap_or_else(|e| panic!("{}: {e}", live.host));
    }
    assert_eq!(LIVE.len(), 3, "the vectors went missing");
}

/// **The encoding check.**
///
/// RFC 9215 section 4.3 puts the coordinates little endian inside an
/// OCTET STRING inside a BIT STRING. A reader that got the byte order
/// backwards, or that skipped a layer of wrapping, produces two numbers
/// of the right length - and `y^2 = x^3 + ax + b` is what says they are
/// not a point.
///
/// This is the only independent check of that encoding in the
/// repository: every other GOST certificate here was written by
/// `x509::builder`, which reads back whatever it wrote.
#[test]
fn test_every_public_key_is_a_point_on_its_curve() {
    let mut checked = 0;
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        let (curve_name, x, y, legacy) = match &leaf.public_key {
            PublicKey::Gost { curve, x, y, legacy, .. } =>
                (*curve, x.clone(), y.clone(), *legacy),
            other => panic!("{}: not a GOST key: {other:?}", live.host),
        };
        assert_eq!(curve_name, live.curve, "{}", live.host);
        assert_eq!(legacy, live.legacy, "{}: the generation", live.host);

        let curve = curves::by_name(curve_name).unwrap();
        let point = allcrypt::ec::Point::new(x.clone(), y.clone());
        assert!(curve.is_on_curve(&point),
                "{}: the certificate's key is not on {curve_name}",
                live.host);
        // And a real key, not the identity or a small-order point.
        curve.validate(&point)
            .unwrap_or_else(|e| panic!("{}: {e}", live.host));

        // **The byte order, isolated.** Reversing both coordinates is
        // the mistake this encoding invites, and on a real key it must
        // not also land on the curve. A coordinate that is palindromic
        // would make this vacuous, so the values are checked to differ.
        let flip = |value: &BigUint| {
            let mut bytes = value.to_bytes_be_padded(curve.field_bytes()).unwrap();
            bytes.reverse();
            BigUint::from_bytes_be(&bytes)
        };
        let (rx, ry) = (flip(&x), flip(&y));
        assert!(rx != x || ry != y, "{}: the coordinates are palindromes, \
                so the byte order proves nothing here", live.host);
        assert!(!curve.is_on_curve(&allcrypt::ec::Point::new(rx, ry)),
                "{}: the coordinates are a point read either way round, \
                 so this proves nothing", live.host);
        checked += 1;
    }
    assert_eq!(checked, 3);
}

/// **The parameter-set OIDs, which the curve name cannot express.**
///
/// This is the test that pins the distinction. `1.2.643.2.2.35.1`
/// (CryptoPro-A) and `1.2.643.2.2.36.0` (CryptoPro-XchA) are the *same*
/// domain parameters under two OIDs - same p, a, b, q, same generator -
/// so both come out of this reader as `gost256-a` and every check above
/// passes either way. Two of these three certificates are on **XchA**,
/// and a ClientKeyExchange whose ephemeral key said A got a fatal
/// `decode_error` from all of them.
///
/// The failing field was in these fixtures the whole time. What was
/// missing was a test that looked at it. The curve name alone reads as
/// `gost256-a` for both spellings, so a certificate on XchA looks like
/// one this library handles perfectly.
#[test]
fn test_the_parameter_sets_are_not_all_canonical() {
    const CRYPTOPRO_A: &str = "1.2.643.2.2.35.1";
    const CRYPTOPRO_XCHA: &str = "1.2.643.2.2.36.0";

    let mut exchange_sets = 0;
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        let param_set = match &leaf.public_key {
            PublicKey::Gost { param_set, .. } => param_set.to_string(),
            other => panic!("{}: not a GOST key: {other:?}", live.host),
        };
        assert_eq!(param_set, live.param_set, "{}", live.host);
        if param_set == CRYPTOPRO_XCHA {
            exchange_sets += 1;
        }
    }

    // **The assertion that makes this fixture set worth having.** If a
    // refetch ever replaced all three with canonical spellings, every
    // other test here would still pass and this one would fail loudly -
    // which is the warning that the corpus has stopped covering the bug
    // it was collected for.
    assert!(exchange_sets >= 2,
            "only {exchange_sets} of these certificates are on an exchange \
             parameter set; the canonicalisation bug would no longer be \
             caught by this corpus");

    // And the curve name really is the same on both spellings, which is
    // what made the OID the only place the difference lived.
    let names: Vec<&str> = LIVE.iter()
        .filter(|live| live.param_set == CRYPTOPRO_XCHA)
        .map(|live| live.curve)
        .collect();
    assert!(names.iter().all(|name| *name == "gost256-a"), "{names:?}");
    assert_ne!(CRYPTOPRO_A, CRYPTOPRO_XCHA);
}

/// The ephemeral key we would send these servers carries **their** OID.
///
/// `gost_kex::encode_public_key_like` copies the peer's
/// `AlgorithmIdentifier` instead of writing the canonical one, and this
/// checks it against the three real ones rather than against a
/// certificate we generated - where our writer and our reader agree by
/// construction and the canonical spelling is the only one that ever
/// appears.
#[test]
fn test_the_ephemeral_key_we_would_send_echoes_their_parameter_set() {
    use allcrypt::tls::gost_kex;

    let mut checked = 0;
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        let (curve_name, x, y, algorithm_id) = match &leaf.public_key {
            PublicKey::Gost { curve, x, y, algorithm_id, .. } =>
                (*curve, x.clone(), y.clone(), *algorithm_id),
            other => panic!("{}: not a GOST key: {other:?}", live.host),
        };
        let curve = curves::by_name(curve_name).unwrap();
        // Their own point, which is certainly on the curve. This test is
        // about the wrapper around the point, not the point.
        let point = allcrypt::ec::Point::new(x, y);
        let spki = gost_kex::encode_public_key_like(algorithm_id, &curve, &point)
            .unwrap_or_else(|e| panic!("{}: {e}", live.host));

        // The peer's AlgorithmIdentifier appears in our SPKI verbatim.
        assert!(spki.windows(algorithm_id.len()).any(|w| w == algorithm_id),
                "{}: our ephemeral key does not carry their \
                 AlgorithmIdentifier", live.host);

        // And for the XchA certificates, the canonical OID must be
        // **absent** - otherwise this would pass on an encoder that
        // wrote both, which is the shape a "fix" that appends rather
        // than replaces would take.
        if live.param_set == "1.2.643.2.2.36.0" {
            let canonical: &[u8] = &[0x2a, 0x85, 0x03, 0x02, 0x02, 0x23, 0x01];
            assert!(!spki.windows(canonical.len()).any(|w| w == canonical),
                    "{}: the canonical CryptoPro-A OID is still in there",
                    live.host);
        }
        checked += 1;
    }
    assert_eq!(checked, 3);
}

/// The names, which is what the parser used to refuse.
///
/// Every one of these certificates carries something no generated one
/// does: Cyrillic text, a multi-RDN subject, and attribute types from
/// Russia's own OID arc.
#[test]
fn test_the_names_decode() {
    use allcrypt::x509::oids;

    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();

        let common_name = leaf.subject.get(oids::COMMON_NAME)
            .unwrap_or_else(|| panic!("{}: no common name", live.host));
        assert!(!common_name.is_empty());

        if let Some(fragment) = live.cyrillic {
            assert!(common_name.contains(fragment),
                    "{}: the subject did not decode: {common_name:?}",
                    live.host);
            assert!(!common_name.is_ascii(),
                    "{}: nothing here is non-ASCII, so the decoding is \
                     not being tested", live.host);
        }

        // Every one names an organisation in its issuer, which is where
        // the Russian-arc attributes sit beside it.
        assert!(leaf.issuer.get(oids::ORGANIZATION).is_some(),
                "{}: no issuer organisation", live.host);
    }

    // **Cyrillic on both sides of the certificate, across the set.**
    // Not per certificate: `www.cryptopro.ru` is issued by a CA that
    // writes its own name in ASCII, and the two test-CA certificates
    // have an ASCII subject. Asserted over the set so the decoding is
    // exercised in both positions without claiming something untrue
    // about any one of them - and asserted at all because a decoder
    // that returned empty strings would satisfy every check above.
    let mut cyrillic_subjects = 0;
    let mut cyrillic_issuers = 0;
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        if !leaf.subject.get(oids::COMMON_NAME).unwrap().is_ascii() {
            cyrillic_subjects += 1;
        }
        if !leaf.issuer.get(oids::ORGANIZATION).unwrap().is_ascii() {
            cyrillic_issuers += 1;
        }
    }
    assert!(cyrillic_subjects > 0, "no subject decoded to non-ASCII");
    assert!(cyrillic_issuers > 0, "no issuer decoded to non-ASCII");
}

/// The attribute types these carry that nothing else here does.
///
/// `1.2.643.100.1` is an OGRN and `1.2.643.100.4` an INN - Russian
/// registration numbers, under Russia's own OID arc. They appear as
/// ordinary DN attributes, and a name parser that only knew the
/// `2.5.4.*` types would have to fall back to printing the OID, which
/// is what `Attribute::label` does. Checked because these are the
/// certificates that made it matter.
#[test]
fn test_the_russian_arc_attributes() {
    let ogrn: &[u8] = &[0x2a, 0x85, 0x03, 0x64, 0x01];           // 1.2.643.100.1
    let mut seen = 0;
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        if let Some(value) = leaf.issuer.get(ogrn) {
            assert!(value.chars().all(|c| c.is_ascii_digit()),
                    "{}: an OGRN that is not digits: {value:?}", live.host);
            seen += 1;
        }
    }
    assert!(seen >= 2, "only {seen} certificates carry an OGRN");
}

/// Each one matches the host it was served for, and not a neighbour.
///
/// A hostname check that accepted everything would pass the first half
/// of this and fail the second, which is why both are here.
#[test]
fn test_hostname_matching_against_real_sans() {
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        assert!(allcrypt::x509::verify::matches_hostname(&leaf, live.host),
                "{}: does not match its own host", live.host);
        assert!(!allcrypt::x509::verify::matches_hostname(&leaf, "example.test"),
                "{}: matches a host it has nothing to do with", live.host);
    }

    // The wildcard one, because `*.cryptopro.ru` is the only real
    // wildcard SAN in the repository that somebody else wrote.
    let wildcard = Certificate::parse(LIVE[2].der).unwrap();
    assert!(allcrypt::x509::verify::matches_hostname(&wildcard, "www.cryptopro.ru"));
    assert!(allcrypt::x509::verify::matches_hostname(&wildcard, "cryptopro.ru"));
    // One label only: a wildcard does not span a dot.
    assert!(!allcrypt::x509::verify::matches_hostname(&wildcard, "a.b.cryptopro.ru"));
}

/// The SANs include IP addresses, including IPv6 - which nothing else
/// here has from a real issuer.
#[test]
fn test_the_ip_address_sans() {
    let leaf = Certificate::parse(LIVE[0].der).unwrap();
    let addresses: Vec<&[u8]> = leaf.extensions.subject_alt_names.iter()
        .filter_map(|name| match name {
            GeneralName::IpAddress(bytes) => Some(*bytes),
            _ => None,
        }).collect();
    assert_eq!(addresses.len(), 2, "one IPv4 and one IPv6");
    assert!(addresses.iter().any(|a| a.len() == 4), "no IPv4 address");
    assert!(addresses.iter().any(|a| a.len() == 16), "no IPv6 address");

    // **Four bytes here, not eight.** An iPAddress inside a name
    // constraint is address *and* mask; in a SAN it is the address
    // alone, and a parser that took the constraint's lengths would
    // refuse both of these.
    assert!(allcrypt::x509::verify::matches_hostname(&leaf, "193.37.157.96"));
    assert!(!allcrypt::x509::verify::matches_hostname(&leaf, "193.37.157.97"));
}

/// The signature algorithms, which are not all the same.
///
/// `tlsgost-512`'s certificate carries a **512 bit key signed with the
/// 256 bit algorithm**, and `www.cryptopro.ru`'s is the other way
/// round. The key's size and the signature's are independent - they are
/// the subject's and the issuer's - and a reader that took one from the
/// other would be right on one of these and wrong on the other.
#[test]
fn test_the_signature_algorithms() {
    use allcrypt::x509::SignatureAlgorithm;

    let algorithms: Vec<SignatureAlgorithm> = LIVE.iter()
        .map(|live| Certificate::parse(live.der).unwrap().signature_algorithm)
        .collect();

    assert!(algorithms.iter().any(|a| matches!(a, SignatureAlgorithm::Gost(256))),
            "no certificate is signed with the 256 bit algorithm: {algorithms:?}");
    assert!(algorithms.iter().any(|a| matches!(a, SignatureAlgorithm::Gost(512))),
            "no certificate is signed with the 512 bit algorithm: {algorithms:?}");

    // The 512 bit *key* is signed with the 256 bit algorithm, which is
    // the pairing that looks like a mistake and is not.
    let big = Certificate::parse(LIVE[1].der).unwrap();
    assert!(matches!(big.public_key, PublicKey::Gost { curve: "gost512-a", .. }));
    assert!(matches!(big.signature_algorithm, SignatureAlgorithm::Gost(256)),
            "{:?}", big.signature_algorithm);
}

/// Nothing in them is refused as unreadable, and nothing critical is
/// unrecognised - which is what would stop a chain being built.
#[test]
fn test_no_unrecognised_critical_extension() {
    for live in LIVE {
        let leaf = Certificate::parse(live.der).unwrap();
        assert!(leaf.extensions.unrecognised_critical.is_empty(),
                "{}: unrecognised critical extensions {:?}",
                live.host, leaf.extensions.unrecognised_critical);
        assert!(!leaf.extensions.is_ca(),
                "{}: a server certificate claims to be a CA", live.host);
    }
}
