/*
FIPS 203's two samplers: `SampleNTT` and `SamplePolyCBD`.

Both turn a seed into a polynomial, and they are not interchangeable.
`SampleNTT` produces something indistinguishable from uniform over the
whole ring and is used for the public matrix `A`, which is why it can be
regenerated from a 32 byte seed instead of transmitted. `SamplePolyCBD`
produces small coefficients from a centred binomial distribution and is
used for the secrets and the noise, where smallness is the whole point -
the scheme's correctness depends on the error staying below `q/4`.

# Pitfalls

**`SampleNTT` must consume exactly three bytes per attempt and read two
twelve bit values out of them.** A sampler that reads two bytes per
coefficient, or three bytes per coefficient, produces a perfectly good
uniform distribution and a different matrix - so two implementations
disagree about `A` and nothing interoperates, with no error anywhere. The
split is `d1 = C0 + 256*(C1 mod 16)` and `d2 = (C1 div 16) + 16*C2`: the
middle byte is shared, its low nibble going to the first value and its
high nibble to the second.

**Rejection is per value, not per triple.** If `d1 < q` it is kept; `d2`
is then tested on its own. Discarding both when either is too large
changes which bytes feed the next coefficient and therefore the whole
polynomial. The second `if` also needs its own `j < 256` guard, or the
last triple of a polynomial can write a 257th coefficient.

**The output of `SampleNTT` is already in the NTT domain** - the name says
so and it is easy to miss. It must not be transformed again. `A_hat` is
used directly in the matrix product; running `ntt` over it produces a
matrix that is self-consistent and wrong.

**`A_hat[i][j]` is sampled from `XOF(rho, j, i)`** - the indices go into
the seed in the opposite order to their position in the matrix. FIPS 203
writes it that way so that the transpose can be generated by swapping the
two bytes rather than by transposing a matrix, which encapsulation needs.
Getting it the obvious way round gives `A` transposed: key generation and
encapsulation then disagree, and every decapsulation returns the implicit
rejection secret rather than the right one - which looks like a correct
implementation of the failure path rather than a bug.

**`SamplePolyCBD` subtracts two sums of bits**, `x - y`, and the result is
taken mod `q`, so a negative difference becomes a value near `q`. Taking
the absolute value, or clamping, gives a distribution that is not centred
and secrets that are not small in the way the proof needs.

**The bit order is `BytesToBits`, little-endian within each byte**, the
same convention as `encode`. A big-endian reading gives a different
polynomial from the same seed.
*/

use crate::hash_functions::keccak::Keccak;
use crate::hash_functions::HashFunction;

use super::ring::{Poly, Q, N};

/// `XOF(rho, i, j)`: SHAKE-128 over the seed and two index bytes.
///
/// Returned as a `Keccak` rather than a byte buffer because `SampleNTT`
/// cannot know in advance how much it needs - rejection sampling consumes
/// an unbounded number of three byte blocks, and in principle a seed could
/// need far more than any fixed buffer. Squeezing on demand is what the
/// standard's `XOF.Squeeze` is.
fn xof(rho: &[u8], i: u8, j: u8) -> Result<Keccak, String> {
    let mut sponge = Keccak::shake(128, 32)?;
    sponge.update(rho);
    sponge.update(&[i, j]);
    Ok(sponge)
}

/// FIPS 203 algorithm 7, `SampleNTT`: a uniform polynomial, already in the
/// NTT domain.
///
/// `rho` is the 32 byte public seed; `i` and `j` are the matrix indices as
/// the standard orders them - see the note at the top of this file about
/// which way round they go.
pub fn sample_ntt(rho: &[u8], i: u8, j: u8) -> Result<Poly, String> {
    if rho.len() != 32 {
        return Err(format!("SampleNTT: rho is {} bytes and should be 32.",
                           rho.len()));
    }
    let sponge = xof(rho, i, j)?;

    // `squeeze` is non-destructive and starts from the beginning each
    // time, so the whole stream is taken at once and then walked. The
    // length is a budget rather than a guess: each three bytes yields up
    // to two coefficients, so 384 bytes would suffice if nothing were
    // rejected, and the chance of needing more than 3,072 is far below
    // any probability this library cares about. If it ever is not enough
    // the function says so rather than returning a short polynomial.
    let stream = sponge.squeeze(3072);

    let mut poly = Poly::zero();
    let mut at = 0usize;
    let mut taken = 0usize;
    while taken < N {
        if at + 3 > stream.len() {
            return Err(format!(
                "SampleNTT: rejection sampling wanted more than {} bytes for \
                 seed index ({i}, {j}), which should not happen - either the \
                 twelve bit split is wrong or the stream is not SHAKE-128.",
                stream.len()));
        }
        let (c0, c1, c2) = (stream[at] as u16, stream[at + 1] as u16,
                            stream[at + 2] as u16);
        at += 3;

        // The middle byte is shared: its low nibble finishes d1 and its
        // high nibble starts d2.
        let d1 = c0 + 256 * (c1 & 0x0f);
        let d2 = (c1 >> 4) + 16 * c2;

        // Two independent tests, not one. And the second needs its own
        // bound check or it can write past the end.
        if d1 < Q {
            poly.coefficients[taken] = d1;
            taken += 1;
        }
        if d2 < Q && taken < N {
            poly.coefficients[taken] = d2;
            taken += 1;
        }
    }
    Ok(poly)
}

/// `PRF_eta(s, b)`: SHAKE-256 over a 32 byte seed and one counter byte,
/// squeezed to `64 * eta` bytes.
fn prf(eta: u32, seed: &[u8], counter: u8) -> Result<Vec<u8>, String> {
    if seed.len() != 32 {
        return Err(format!("PRF: the seed is {} bytes and should be 32.",
                           seed.len()));
    }
    let length = 64 * eta as usize;
    let mut sponge = Keccak::shake(256, length)?;
    sponge.update(seed);
    sponge.update(&[counter]);
    Ok(sponge.squeeze(length))
}

/// FIPS 203 algorithm 8, `SamplePolyCBD_eta`: small coefficients from a
/// centred binomial distribution.
///
/// Each coefficient is the difference of two sums of `eta` bits, so it
/// lies in `[-eta, eta]` and is taken mod `q` - a negative value becomes
/// one just below `q`, which is the representation the rest of the
/// library uses.
pub fn sample_poly_cbd(eta: u32, seed: &[u8], counter: u8)
        -> Result<Poly, String> {
    if eta != 2 && eta != 3 {
        return Err(format!(
            "SamplePolyCBD: FIPS 203 uses eta 2 and 3, not {eta}."));
    }
    let bytes = prf(eta, seed, counter)?;
    debug_assert_eq!(bytes.len(), 64 * eta as usize);

    let bit = |index: usize| -> u16 {
        ((bytes[index / 8] >> (index % 8)) & 1) as u16
    };

    let mut poly = Poly::zero();
    for at in 0..N {
        let base = 2 * at * eta as usize;
        let mut x = 0u16;
        let mut y = 0u16;
        for step in 0..eta as usize {
            x += bit(base + step);
            y += bit(base + eta as usize + step);
        }
        // `x - y` mod q, without going through a signed type.
        poly.coefficients[at] = (x + Q - y) % Q;
    }
    Ok(poly)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `SampleNTT` produces something reduced, and different seeds give
    /// different polynomials.
    #[test]
    fn test_sample_ntt_is_reduced_and_depends_on_every_input() {
        let rho = [0x5au8; 32];
        let base = sample_ntt(&rho, 0, 0).unwrap();
        assert!(base.is_reduced());
        // Not all one value, which a broken rejection loop could produce.
        let distinct: std::collections::HashSet<u16> =
            base.coefficients.iter().copied().collect();
        assert!(distinct.len() > 200,
                "a uniform polynomial should have few repeats, saw {} \
                 distinct values", distinct.len());

        // **The two index bytes are not interchangeable.** This is the
        // transpose trap from the top of this file: if (i, j) and (j, i)
        // gave the same polynomial, generating A and its transpose would
        // be the same operation and the bug would be invisible.
        assert_ne!(sample_ntt(&rho, 0, 1).unwrap(),
                   sample_ntt(&rho, 1, 0).unwrap(),
                   "XOF(rho, i, j) must differ from XOF(rho, j, i)");

        // And the seed matters.
        let mut other = rho;
        other[31] ^= 1;
        assert_ne!(sample_ntt(&other, 0, 0).unwrap(), base);

        assert!(sample_ntt(&[0u8; 31], 0, 0).unwrap_err().contains("32"));
    }

    /// The twelve bit split is a little-endian bit stream read twelve bits
    /// at a time, and the byte formula agrees with reading it that way.
    ///
    /// Two formulations of the same specification, compared over the real
    /// SHAKE output: `sample_ntt`'s
    /// `d1 = C0 + 256*(C1 mod 16)`, `d2 = (C1 div 16) + 16*C2` against a
    /// bit-level reader that accumulates bits least significant first and
    /// takes twelve at a time. They are the same thing said differently,
    /// so agreeing is evidence about the byte arithmetic - and if the two
    /// nibbles of the middle byte were swapped, or the halves exchanged,
    /// they would disagree on nearly every triple.
    ///
    /// A first version of this test asserted the formula on hand-picked
    /// constants, which clippy correctly called a constant expression: it
    /// restated the formula rather than checking anything the code does.
    #[test]
    fn test_the_twelve_bit_split_agrees_with_a_bit_level_reader() {
        let rho = [0x3cu8; 32];
        let (i, j) = (2u8, 5u8);
        let stream = xof(&rho, i, j).unwrap().squeeze(3072);

        // The bit-level reading: bit `n` of the stream is
        // `(stream[n / 8] >> (n % 8)) & 1`, and a twelve bit field is
        // twelve consecutive bits, least significant first.
        let field = |index: usize| -> u16 {
            let mut value = 0u16;
            for bit in 0..12 {
                let at = index * 12 + bit;
                value |= (((stream[at / 8] >> (at % 8)) & 1) as u16) << bit;
            }
            value
        };

        // Same rejection loop, driven by the other reader.
        let mut expected = Vec::with_capacity(N);
        let mut index = 0usize;
        while expected.len() < N {
            let value = field(index);
            index += 1;
            if value < Q {
                expected.push(value);
            }
        }

        let poly = sample_ntt(&rho, i, j).unwrap();
        assert_eq!(&poly.coefficients[..], &expected[..],
                   "the byte formula and a bit-level reading of the same \
                    stream should give the same polynomial");

        // And the two readings really are distinguishable: a swapped pair
        // of nibbles in the middle byte would change the first field, so
        // this is not an identity.
        let (c0, c1, c2) = (stream[0] as u16, stream[1] as u16,
                            stream[2] as u16);
        assert_eq!(field(0), c0 + 256 * (c1 & 0x0f));
        assert_eq!(field(1), (c1 >> 4) + 16 * c2);
        assert_ne!(field(0), c0 + 256 * (c1 >> 4),
                   "the low nibble of the middle byte belongs to the first \
                    field, and the stream here distinguishes the two");
    }

    /// Rejection actually happens: over many seeds, some triples are
    /// discarded, so the stream consumed is longer than 384 bytes.
    ///
    /// Stated as a test because a sampler that never rejects is one whose
    /// bound check is wrong - every twelve bit value below 4096 would be
    /// accepted, including the 767 that are not coefficients.
    #[test]
    fn test_values_at_or_above_q_are_rejected() {
        // Count how many of the 4096 twelve bit values a correct sampler
        // must discard. 4096 - 3329 = 767, about 19%, so over 256
        // coefficients a rejection is overwhelmingly likely.
        assert_eq!(4096 - Q as u32, 767);

        // Every coefficient of every sampled polynomial is below q, which
        // is the observable consequence.
        for index in 0..8u8 {
            let poly = sample_ntt(&[index; 32], index, index ^ 1).unwrap();
            assert!(poly.coefficients.iter().all(|value| *value < Q));
        }
    }

    /// `SamplePolyCBD` produces small coefficients, centred, in the
    /// representation the rest of the library uses.
    #[test]
    fn test_sample_poly_cbd_is_small_and_centred() {
        for eta in [2u32, 3] {
            let poly = sample_poly_cbd(eta, &[0x11u8; 32], 0).unwrap();
            assert!(poly.is_reduced());

            // Every coefficient is in [-eta, eta], which in this
            // representation means below eta or at least q - eta.
            for (at, value) in poly.coefficients.iter().enumerate() {
                let centred = if *value > Q / 2 {
                    *value as i32 - Q as i32
                } else {
                    *value as i32
                };
                assert!(centred.unsigned_abs() <= eta,
                        "eta = {eta}: coefficient {at} is {centred}, which is \
                         outside [-{eta}, {eta}]");
            }

            // Centred means the mean is near zero and both signs appear.
            let negatives = poly.coefficients.iter()
                .filter(|value| **value > Q / 2).count();
            let positives = poly.coefficients.iter()
                .filter(|value| **value != 0 && **value <= Q / 2).count();
            assert!(negatives > 40 && positives > 40,
                    "eta = {eta}: {negatives} negative and {positives} \
                     positive coefficients - a distribution this lopsided \
                     suggests the subtraction is being clamped or made \
                     absolute");

            // The counter byte is part of the input.
            assert_ne!(sample_poly_cbd(eta, &[0x11u8; 32], 1).unwrap(), poly);
        }
    }

    /// The centred binomial distribution has the shape it should.
    ///
    /// For eta = 2 the probabilities are 1/16, 4/16, 6/16, 4/16, 1/16 over
    /// -2..2, so zero should be about three eighths of the coefficients
    /// and the extremes about one sixteenth each. Checked loosely over
    /// several seeds - the point is to catch a distribution that is
    /// uniform or one-sided, not to test the generator's statistics.
    #[test]
    fn test_the_binomial_distribution_has_the_right_shape() {
        let mut counts = [0usize; 5];
        let mut total = 0usize;
        for counter in 0..16u8 {
            let poly = sample_poly_cbd(2, &[0x77u8; 32], counter).unwrap();
            for value in poly.coefficients {
                let centred = if value > Q / 2 {
                    value as i32 - Q as i32
                } else {
                    value as i32
                };
                counts[(centred + 2) as usize] += 1;
                total += 1;
            }
        }
        let share = |index: usize| counts[index] as f64 / total as f64;
        assert!((share(2) - 0.375).abs() < 0.05,
                "zero should be about 3/8, saw {:.3}", share(2));
        assert!((share(1) - 0.25).abs() < 0.05, "{:.3}", share(1));
        assert!((share(3) - 0.25).abs() < 0.05, "{:.3}", share(3));
        assert!((share(0) - 0.0625).abs() < 0.03, "{:.3}", share(0));
        assert!((share(4) - 0.0625).abs() < 0.03, "{:.3}", share(4));
    }

    #[test]
    fn test_the_parameters_are_checked() {
        assert!(sample_poly_cbd(1, &[0u8; 32], 0).unwrap_err()
                    .contains("eta 2 and 3"));
        assert!(sample_poly_cbd(4, &[0u8; 32], 0).unwrap_err()
                    .contains("eta 2 and 3"));
        assert!(sample_poly_cbd(2, &[0u8; 31], 0).unwrap_err().contains("32"));
    }

    /// The PRF squeezes `64 * eta` bytes, which is what makes `eta` change
    /// the amount of randomness rather than only its interpretation.
    #[test]
    fn test_the_prf_length_follows_eta() {
        assert_eq!(prf(2, &[0u8; 32], 0).unwrap().len(), 128);
        assert_eq!(prf(3, &[0u8; 32], 0).unwrap().len(), 192);
        // And a longer squeeze is not a prefix of a shorter one's output
        // being padded - SHAKE at two lengths from one seed agrees on the
        // prefix, so this checks the opposite: that the first 128 bytes
        // *do* match, which is a property of SHAKE and worth pinning
        // because a PRF built on a fixed-output hash would not have it.
        assert_eq!(&prf(3, &[0u8; 32], 0).unwrap()[..128],
                   &prf(2, &[0u8; 32], 0).unwrap()[..]);
    }
}
