#!/usr/bin/env python3
"""Compile and run every code block in the documentation.

Docs rot silently. This makes them fail loudly instead: each fenced ```rust
block in README.md and docs/*.md is compiled as part of a generated example,
and each ```python block is executed against the built module.

    python3 scripts/check_docs.py              # rust blocks (+ python if built)
    python3 scripts/check_docs.py --rust       # rust only
    python3 scripts/check_docs.py --python     # python only

Tag a block ```rust,ignore or ```python,ignore to skip it - only for
genuinely illustrative fragments that are not meant to run.
"""

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = [ROOT / "README.md"] + sorted((ROOT / "docs").glob("*.md"))
GENERATED = ROOT / "examples" / "doc_examples.rs"

FENCE = re.compile(r"^```(\w+)([^\n]*)\n(.*?)^```", re.M | re.S)


def blocks(lang):
    """Yield (source_file, index, code) for each non-ignored block of `lang`."""
    for path in DOCS:
        if not path.exists():
            continue
        for i, m in enumerate(FENCE.finditer(path.read_text(encoding="utf-8"))):
            tag, rest, code = m.group(1), m.group(2), m.group(3)
            if tag != lang or "ignore" in rest:
                continue
            yield path.relative_to(ROOT), i, code


def check_rust():
    parts = [
        "// GENERATED by scripts/check_docs.py - do not edit.",
        "// Every function below is one fenced ```rust block from the docs.",
        "#![allow(unused_variables, unused_mut, unused_imports, dead_code, non_snake_case)]",
        "",
    ]
    names = []
    for path, i, code in blocks("rust"):
        fn = "doc_%s_%d" % (re.sub(r"\W", "_", str(path)), i)
        names.append((fn, path))
        body = "\n".join("    " + line for line in code.rstrip().splitlines())
        parts.append("/// From %s block %d" % (path, i))
        parts.append("fn %s() -> Result<(), String> {" % fn)
        parts.append(body)
        parts.append("    Ok(())")
        parts.append("}")
        parts.append("")

    parts.append("fn main() {")
    for fn, path in names:
        parts.append('    %s().unwrap_or_else(|e| panic!("{} failed: {}", "%s", e));'
                     % (fn, path))
    parts.append('    println!("all {} documentation examples ran", %d);' % len(names))
    parts.append("}")

    GENERATED.parent.mkdir(exist_ok=True)
    GENERATED.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print("extracted %d rust blocks -> %s" % (len(names), GENERATED.relative_to(ROOT)))

    cmd = ["cargo", "run", "--quiet", "--example", "doc_examples"]
    if "--offline" in sys.argv:
        cmd.insert(1, "--offline")
    r = subprocess.run(cmd, cwd=ROOT)

    # **Removed on success, and this is not tidiness.**
    #
    # cargo auto-discovers `examples/*.rs`, so while this file exists it is
    # compiled by every `cargo build`, `cargo test` and `cargo clippy` -
    # and it is only regenerated here. Change a signature the docs use, run
    # `cargo test` without running this script first, and the workspace
    # stops compiling with an error inside a file nobody wrote:
    #
    #     error[E0061]: this function takes 6 arguments but 5 were supplied
    #        --> examples/doc_examples.rs:626:32
    #
    # which is a stale artifact rather than anything wrong with the tree.
    # That is how it was reported. It is invisible to anyone who runs this
    # script before `cargo test`, because doing so regenerates the file -
    # so the person who habitually runs the whole gate never sees it and
    # the person who runs one command does.
    #
    # Gating the target behind a cargo feature does not work: cargo checks
    # a declared `[[example]]`'s path when it parses the manifest, feature
    # or no feature, so a fresh clone without this file would fail to parse
    # Cargo.toml at all. Not leaving the file behind is the fix.
    #
    # **Kept on failure**, because that is when somebody wants to read it -
    # the line number in the error refers to it. The message says so, and
    # says that `cargo test` will keep failing until the docs are fixed,
    # which at that point is true and is the point.
    if r.returncode == 0:
        GENERATED.unlink(missing_ok=True)
    else:
        print("\nthe generated example is kept at %s so the line numbers "
              "above mean something." % GENERATED.relative_to(ROOT))
        print("cargo build and cargo test will keep failing on it until the "
              "doc block is fixed;")
        print("deleting it makes them build again without fixing anything.")
    return r.returncode


def check_python():
    # `python/` is where scripts/build_python.py puts the module, so a
    # plain `python3 scripts/check_docs.py` works with no PYTHONPATH. An
    # installed copy still wins, since sys.path is searched in order and
    # this goes on the end.
    sys.path.append(str(ROOT / "python"))
    try:
        import allcrypt  # noqa: F401
    except ImportError:
        print("SKIP python blocks: the allcrypt module is not importable "
              "(run `python3 scripts/build_python.py` first)")
        return 0

    failures = 0
    count = 0
    for path, i, code in blocks("python"):
        count += 1
        try:
            exec(compile(code, "%s#block%d" % (path, i), "exec"), {"__name__": "__doc__"})
        except Exception as exc:
            failures += 1
            print("FAIL %s block %d: %s: %s" % (path, i, type(exc).__name__, exc))
    print("ran %d python blocks, %d failed" % (count, failures))
    return 1 if failures else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rust", action="store_true")
    ap.add_argument("--python", action="store_true")
    ap.add_argument("--offline", action="store_true")
    args, _ = ap.parse_known_args()
    do_rust = args.rust or not args.python
    do_py = args.python or not args.rust

    rc = 0
    if do_rust:
        rc |= check_rust()
    if do_py:
        rc |= check_python()
    return rc


if __name__ == "__main__":
    sys.exit(main())
