#!/usr/bin/env python3
"""Write vectors/unix_crypt.vec: known answers for the crypt(3) hashes.

Two independent sources agree on every row. The answers come from
libxcrypt's `test/ka-table.inc`, which its header says was generated by
**Passlib**'s pure-Python back ends - not by libxcrypt itself - precisely
so the C library is tested against a different implementation. This
script fetches that table at tag v4.4.36, keeps the methods this library
implements, and additionally requires the system's `libcrypt` (ctypes) to
reproduce each row before writing it. So a row is a value Passlib and
libxcrypt agree on, checked a third time here.

    python3 scripts/make_unix_crypt_vectors.py

**A development tool, not a test.** It fetches over the network and needs
`libcrypt`; `tests/test_unix_crypt.rs` reads `vectors/unix_crypt.vec`
offline. Each row is `method setting=<c-string> phrase=<hex> expected=<c-string>`:
`crypt(phrase, setting)` must equal `expected`.
"""

import ctypes
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT = os.path.join(ROOT, "vectors", "unix_crypt.vec")
TABLE_URL = "https://raw.githubusercontent.com/besser82/libxcrypt/v4.4.36/test/ka-table.inc"

# libxcrypt's INCLUDE_<name> -> this library's method name.
METHODS = {
    "descrypt": "descrypt", "bsdicrypt": "bsdicrypt", "bigcrypt": "bigcrypt",
    "md5crypt": "md5crypt", "bcrypt": "bcrypt", "bcrypt_a": "bcrypt",
    "bcrypt_x": "bcrypt", "bcrypt_y": "bcrypt", "nt": "nt",
    "sha1crypt": "sha1crypt", "sha256crypt": "sha256crypt",
    "sha512crypt": "sha512crypt", "sunmd5": "sunmd5",
}

lib = ctypes.CDLL("libcrypt.so.1")
lib.crypt.restype = ctypes.c_char_p


def decode_c_string(s):
    """A C string literal's bytes, handling \\xHH, octal \\NNN and the
    usual single-character escapes."""
    out = bytearray()
    i = 0
    while i < len(s):
        c = s[i]
        if c != "\\":
            out.append(ord(c))
            i += 1
            continue
        n = s[i + 1]
        if n == "x":
            out.append(int(s[i + 2:i + 4], 16))
            i += 4
        elif n in "01234567":
            j = i + 1
            while j < len(s) and j < i + 4 and s[j] in "01234567":
                j += 1
            out.append(int(s[i + 1:j], 8) & 0xFF)
            i = j
        else:
            out.append({"n": 10, "t": 9, "r": 13, "\\": 92, '"': 34, "0": 0}[n])
            i += 2
    return bytes(out)


def parse_table(text):
    rows = []
    current = None
    row = re.compile(r'\s*\{ "((?:[^"\\]|\\.)*)", "((?:[^"\\]|\\.)*)", "((?:[^"\\]|\\.)*)" \},')
    for line in text.splitlines():
        m = re.match(r"#if INCLUDE_(\w+) && defined TEST_\w+", line)
        if m:
            current = m.group(1)
            continue
        m = row.match(line)
        if m and current in METHODS:
            rows.append((METHODS[current], m.group(1), m.group(2), m.group(3)))
    return rows


def main():
    with urllib.request.urlopen(TABLE_URL) as response:
        rows = parse_table(response.read().decode())
    if not rows:
        sys.exit("parsed no rows from the table")

    out_rows = []
    counts = {}
    for method, setting, expected, phrase in rows:
        phrase_bytes = decode_c_string(phrase)
        setting_bytes = decode_c_string(setting)
        # The system libcrypt must agree, as the third witness.
        got = lib.crypt(phrase_bytes, setting_bytes)
        got = got.decode() if got else None
        if got != decode_c_string(expected).decode("latin-1"):
            # A method the local libcrypt was not built with, or a row for
            # a reject case (empty expected): skip, but never on a mismatch.
            if got is not None and expected != "":
                sys.exit(f"libcrypt disagrees: {method} {setting!r} {phrase!r}: "
                         f"{got!r} != {expected!r}")
            continue
        counts[method] = counts.get(method, 0) + 1
        out_rows.append(f"{method} setting={setting} phrase={phrase_bytes.hex() or '-'} "
                        f"expected={expected}")

    header = ("# crypt(3) known answers. Written by scripts/make_unix_crypt_vectors.py;\n"
              "# do not edit. From libxcrypt v4.4.36's test/ka-table.inc, which its\n"
              "# header says Passlib generated (an implementation independent of\n"
              "# libxcrypt), and which the system libcrypt reproduced here. Each row:\n"
              "# crypt(phrase, setting) == expected. setting and expected are C string\n"
              "# literals (\\xHH, octal); phrase is hex, '-' for empty.\n")
    with open(OUTPUT, "w") as f:
        f.write(header)
        for r in out_rows:
            f.write(r + "\n")
    print(f"{len(out_rows)} rows: {counts}")


if __name__ == "__main__":
    main()
