#!/usr/bin/env python3
"""Write vectors/dual_ec.vec: Dual_EC_DRBG as OpenSSL's FIPS module computes it.

Two independent implementations agree on every row. The corpus is
generated by the witness in `scripts/witness/dualecwitness`, which is
OpenSSL FIPS module 2.0.5's `fips_drbg_ec.c` (fetched unchanged from the
tag) built against OpenSSL 1.0.2's libcrypto. Before anything is written
the witness is required to reproduce Bouncy Castle 1.78.1's published
Dual EC test vectors, which were computed from a different source - so a
row is a value OpenSSL and Bouncy Castle agree on, not OpenSSL checked
against itself.

    scripts/witness/dualecwitness/build.sh        # builds /opt/dualecwitness/dualec
    python3 scripts/make_dual_ec_vectors.py

**A development tool, not a test.** It needs the witness and fetches the
Bouncy Castle anchors over the network the first run; `tests/test_dual_ec.rs`
reads `vectors/dual_ec.vec` offline.

Each row drives the sequence the NIST known-answer tests use: instantiate,
generate, optionally reseed, generate again - so the extra `x(s * P)` at
the end of each request, and the reseed's `pad8`, are both exercised.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT = os.path.join(ROOT, "vectors", "dual_ec.vec")
WITNESS = "/opt/dualecwitness/dualec"

# Bouncy Castle 1.78.1's first two SHA-256 / P-256 vectors
# (core/src/test/.../DualECDRBGTest.java), entropy from its SHA256EntropyProvider.
# The anchor: a value computed by an implementation that is not OpenSSL.
BC_ANCHOR = {
    "entropy": "000102030405060708090a0b0c0d0e0f",
    "nonce": "2021222324252627",
    "gen1": "ff5163c388f791e96f1052d5c8f0bd6fbf7144839c4890ff85487c5c12702e4c"
            "9849af518ae68deb14d3a62702bbde4b98ab211765fd87aca12fc2a6",
    "gen2": "9a0a11f2dfb88f7260559dd8da6134eb2b34cc0415fa8fd0474db6b85e1a0838"
            "5f41b435df81296b1b4edf66e0107c0844e3d28a89b05046b89177f2",
}


class Witness:
    def __init__(self):
        self.proc = subprocess.Popen([WITNESS], stdin=subprocess.PIPE,
                                     stdout=subprocess.PIPE, text=True)

    def cmd(self, line):
        self.proc.stdin.write(line + "\n")
        self.proc.stdin.flush()
        return self.proc.stdout.readline().strip()

    def instantiate(self, curve, hash_name, entropy, nonce, pers):
        r = self.cmd(f"new {curve} {hash_name} {entropy or '-'} {nonce or '-'} {pers or '-'}")
        if r != "OK":
            raise RuntimeError(f"instantiate {curve} {hash_name}: {r}")

    def generate(self, nbytes, adin):
        r = self.cmd(f"gen {nbytes} {adin or '-'}")
        if r == "ERR":
            raise RuntimeError("generate failed")
        return r

    def reseed(self, entropy, adin):
        if self.cmd(f"reseed {entropy} {adin or '-'}") != "OK":
            raise RuntimeError("reseed failed")

    def close(self):
        self.proc.stdin.close()
        self.proc.wait()


def material(label, n):
    # Deterministic, so re-running changes nothing unless the witness does.
    import hashlib
    out = b""
    i = 0
    while len(out) < n:
        out += hashlib.sha256(f"dual_ec {label} {i}".encode()).digest()
        i += 1
    return out[:n].hex()


def check_anchor(w):
    w.instantiate("P-256", "SHA256", BC_ANCHOR["entropy"], BC_ANCHOR["nonce"], None)
    g1 = w.generate(len(BC_ANCHOR["gen1"]) // 2, None)
    g2 = w.generate(len(BC_ANCHOR["gen2"]) // 2, None)
    if g1 != BC_ANCHOR["gen1"] or g2 != BC_ANCHOR["gen2"]:
        sys.exit("ct_check: the witness does not reproduce Bouncy Castle's vectors; "
                 "the two implementations disagree, so the corpus would be OpenSSL "
                 "checked against itself.")


# curve, hash, security strength in bytes; the hashes SP 800-90A table 4 allows.
CURVES = [
    ("P-256", ["SHA1", "SHA224", "SHA256", "SHA384", "SHA512"], 16),
    ("P-384", ["SHA224", "SHA256", "SHA384", "SHA512"], 24),
    ("P-521", ["SHA256", "SHA384", "SHA512"], 32),
]
# Output lengths, in bytes, chosen to cross the per-block boundary (30, 46,
# 63 bytes of output per curve) rather than land on it.
LENGTHS = [1, 16, 29, 30, 31, 46, 60, 63, 64, 128]


def main():
    if not os.path.exists(WITNESS):
        sys.exit(f"{WITNESS} is missing; run scripts/witness/dualecwitness/build.sh")
    rows = []
    w = Witness()
    check_anchor(w)
    # The anchor itself, as a row.
    rows.append(f"vector curve=P-256 hash=SHA-256 entropy={BC_ANCHOR['entropy']} "
                f"nonce={BC_ANCHOR['nonce']} pers=- adin1=- out1={BC_ANCHOR['gen1']} "
                f"adin2=- out2={BC_ANCHOR['gen2']} source=bouncycastle")

    for ci, (curve, hashes, strength) in enumerate(CURVES):
        for hi, hash_name in enumerate(hashes):
            entropy = material(f"{curve}{hash_name}ent", strength)
            nonce = material(f"{curve}{hash_name}non", strength // 2)
            # A spread of the options: plain, personalization, additional
            # input on each generate, and a reseed between the two.
            variants = [
                ("plain", None, None, None, None),
                ("pers", material(f"{curve}{hash_name}pers", strength), None, None, None),
                ("adin", None, material(f"{curve}{hash_name}a1", strength),
                 material(f"{curve}{hash_name}a2", strength), None),
                ("reseed", None, None, None, material(f"{curve}{hash_name}re", strength)),
            ]
            for vi, (tag, pers, adin1, adin2, reseed_ent) in enumerate(variants):
                length = LENGTHS[(ci * 4 + hi * 3 + vi) % len(LENGTHS)]
                w.instantiate(curve, hash_name, entropy, nonce, pers)
                out1 = w.generate(length, adin1)
                reseed_adin = None
                if reseed_ent is not None:
                    reseed_adin = material(f"{curve}{hash_name}rea", strength)
                    w.reseed(reseed_ent, reseed_adin)
                out2 = w.generate(length, adin2)
                row = (f"vector curve={curve} hash={dash(dashhash(hash_name))} "
                       f"entropy={entropy} nonce={nonce} pers={pers or '-'} "
                       f"adin1={adin1 or '-'} out1={out1} "
                       f"reseed_entropy={reseed_ent or '-'} reseed_adin={reseed_adin or '-'} "
                       f"adin2={adin2 or '-'} out2={out2}")
                rows.append(row)
    w.close()

    header = ("# Dual_EC_DRBG, as OpenSSL FIPS module 2.0.5 computes it, and Bouncy\n"
              "# Castle 1.78.1 agrees. Written by scripts/make_dual_ec_vectors.py; do\n"
              "# not edit. Each row: instantiate(entropy, nonce, pers), generate(adin1)\n"
              "# = out1, optionally reseed(reseed_entropy, reseed_adin), generate(adin2)\n"
              "# = out2. '-' is empty. The source=bouncycastle row is from a different\n"
              "# implementation; every other row the two agree on.\n")
    with open(OUTPUT, "w") as f:
        f.write(header)
        for row in rows:
            f.write(row + "\n")
    print(f"{len(rows)} rows written to {OUTPUT}")


def dashhash(name):
    return name


def dash(name):
    # "SHA256" -> "SHA-256", "SHA1" -> "SHA-1".
    return "SHA-" + name[3:]


if __name__ == "__main__":
    main()
