"""Private keys read from PEM and DER, against python-cryptography.

**A private-key parser never looks at the public half**, so it will
happily accept a well-shaped forgery: the first version of the Rust unit
tests here used vectors typed from memory, and they parsed, and they
agreed with each other, and `openssl pkey` refused every one of them. A
parser checked only against itself is a parser checked against nothing.

So every key in this file is generated by `cryptography` and the numbers
we read out are compared with the numbers it read out of the same bytes.
Three encodings, both algorithms, PEM and DER:

* PKCS#8 (RFC 5208), `PRIVATE KEY`
* SEC1 (RFC 5915), `EC PRIVATE KEY`
* PKCS#1 (RFC 8017 A.1.2), `RSA PRIVATE KEY`

And the key is *used* afterwards - a signature we make and `cryptography`
verifies - because a scalar off by a byte of padding still looks like a
scalar.
"""

import pathlib

import pytest

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, padding, rsa, utils

import allcrypt

PEM = serialization.Encoding.PEM
DER = serialization.Encoding.DER
PKCS8 = serialization.PrivateFormat.PKCS8
SEC1_OR_PKCS1 = serialization.PrivateFormat.TraditionalOpenSSL
NOTHING = serialization.NoEncryption()

CURVES = [("P-256", ec.SECP256R1(), 32), ("P-384", ec.SECP384R1(), 48),
          ("P-521", ec.SECP521R1(), 66)]


def encodings(key):
    """Every shape `cryptography` will write this key in.

    The labels are spelled out rather than read from `.name`: in
    python-cryptography 50.0 these are no longer Python enums and have
    no `.name`, and the four tests built on this helper failed before
    reading a single key."""
    out = {}
    for encoding_label, encoding in (("PEM", PEM), ("DER", DER)):
        for form_label, form in (("PKCS8", PKCS8),
                                 ("TraditionalOpenSSL", SEC1_OR_PKCS1)):
            out[(encoding_label, form_label)] = key.private_bytes(
                encoding, form, NOTHING)
    return out


# ------------------------------------------------------------------- EC ---

@pytest.mark.parametrize("name,curve,width", CURVES)
def test_every_ec_encoding_gives_the_same_scalar(name, curve, width):
    """Six files, one key.

    PKCS#8 puts the curve in the algorithm identifier and SEC1 puts it
    inside the key, so these are genuinely different structures carrying
    the same number - which is the only reason reading both is worth
    doing, and the only way a mistake in one of them shows.
    """
    key = ec.generate_private_key(curve)
    expected = key.private_numbers().private_value.to_bytes(width, "big")
    for label, blob in encodings(key).items():
        ours = allcrypt.private_key(blob)
        assert isinstance(ours, allcrypt.EcKey), label
        assert ours.curve == name, label
        # Padded to the curve's width, which is what RFC 5915 section 3
        # says the OCTET STRING holds - and what a signature needs.
        assert ours.private_bytes() == expected, label


@pytest.mark.parametrize("name,curve,width", CURVES)
def test_an_ec_key_we_read_still_signs(name, curve, width):
    """The number is right *and* it is the key.

    A scalar off by a byte of leading padding is still a plausible
    scalar, and still parses. Only a signature `cryptography` verifies
    against the public half says the two are the same key.
    """
    key = ec.generate_private_key(curve)
    blob = key.private_bytes(PEM, PKCS8, NOTHING)
    ours = allcrypt.private_key(blob)

    digest = hashes.Hash(hashes.SHA256())
    digest.update(b"read from a file and used")
    digest = digest.finalize()
    # `EcKey.sign` returns `r || s`; `cryptography` wants the DER
    # SEQUENCE, so the two halves are split at the curve's width and
    # re-encoded. Half the length, not a fixed 32, or P-384 silently
    # verifies the wrong numbers.
    raw = ours.sign(digest, "sha256")
    half = len(raw) // 2
    signature = utils.encode_dss_signature(
        int.from_bytes(raw[:half], "big"), int.from_bytes(raw[half:], "big"))
    key.public_key().verify(signature, digest,
                            ec.ECDSA(utils.Prehashed(hashes.SHA256())))


# ------------------------------------------------------------------ RSA ---

def test_every_rsa_encoding_gives_the_same_primes():
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    numbers = key.private_numbers()
    for label, blob in encodings(key).items():
        ours = allcrypt.private_key(blob)
        assert isinstance(ours, allcrypt.RsaKey), label
        parts = ours.numbers
        assert int.from_bytes(parts["e"], "big") == 65537, label
        # p and q may come back either way round - the file says which,
        # and nothing downstream depends on the order - so compare as a
        # set rather than pinning an order this code does not control.
        assert {int.from_bytes(parts["p"], "big"),
                int.from_bytes(parts["q"], "big")} == {numbers.p, numbers.q}, label
        assert int.from_bytes(parts["n"], "big") == numbers.public_numbers.n, label


def test_an_rsa_key_we_read_still_signs():
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    ours = allcrypt.private_key(key.private_bytes(PEM, PKCS8, NOTHING))

    message = b"read from a file and used"
    digest = hashes.Hash(hashes.SHA256())
    digest.update(message)
    signature = ours.sign(digest.finalize(), "sha256")
    key.public_key().verify(signature, message, padding.PKCS1v15(),
                            hashes.SHA256())


def test_the_crt_parameters_in_the_file_are_not_trusted():
    """They are derived from p, q and e rather than read.

    A file whose stored `dP` disagrees with `d mod (p-1)` would otherwise
    produce signatures that fail with nothing here to explain why. This
    corrupts `exponent1` in a real key and asserts the key still works -
    which is only true because that field is recomputed.
    """
    key = rsa.generate_private_key(public_exponent=65537, key_size=1024)
    blob = bytearray(key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING))

    numbers = key.private_numbers()
    wanted = numbers.dmp1.to_bytes((numbers.dmp1.bit_length() + 7) // 8, "big")
    at = bytes(blob).find(wanted)
    assert at > 0, "could not find exponent1 in the DER"
    # **The LAST byte, not the first.** Flipping the low bit of dP's most
    # significant byte was flaky at about one run in four hundred: when
    # that byte is exactly 0x01 - dmp1 of 505 bits, say - the flip makes
    # it 0x00, the INTEGER is then non-minimally encoded, and this
    # library refuses the *file* with "Non-minimal INTEGER encoding"
    # before it ever recomputes anything. Correct of the parser, and a
    # test of the wrong thing.
    #
    # A trailing byte cannot change the encoding's length or its
    # minimality, so the corrupted file stays well-formed and the only
    # thing wrong with it is the value - which is what this test is about.
    blob[at + len(wanted) - 1] ^= 0x01      # flip a bit inside dP

    ours = allcrypt.private_key(bytes(blob))
    message = b"the CRT parameters in the file were wrong"
    digest = hashes.Hash(hashes.SHA256())
    digest.update(message)
    signature = ours.sign(digest.finalize(), "sha256")
    key.public_key().verify(signature, message, padding.PKCS1v15(),
                            hashes.SHA256())


# -------------------------------------------- shapes nothing else writes ---
#
# `cryptography` and `openssl` both write well-formed files, so the checks
# below are unreachable from a generated key and every one of them was a
# MISS in the deliberate-breakage sweep until these existed. Each is built
# by editing a real file, because a hand-built one from scratch would only
# test whatever the test itself encoded.


def _der_parts(blob):
    """Walk one DER SEQUENCE, returning `(tag, header, contents)` triples.

    A tiny reader rather than an import: the point of these tests is to
    make a file `cryptography` would never write, so `cryptography`
    cannot be the thing that writes it.
    """
    assert blob[0] == 0x30
    body, at = _contents(blob, 0)
    out = []
    offset = at
    while offset < at + len(body):
        tag = blob[offset]
        contents, start = _contents(blob, offset)
        out.append((tag, offset, start, contents))
        offset = start + len(contents)
    return out


def _contents(blob, at):
    """The contents of the TLV at `at`, and where they start."""
    length = blob[at + 1]
    if length < 0x80:
        return blob[at + 2:at + 2 + length], at + 2
    count = length & 0x7f
    length = int.from_bytes(blob[at + 2:at + 2 + count], "big")
    start = at + 2 + count
    return blob[start:start + length], start


@pytest.mark.parametrize("name", ["x25519", "x448"])
def test_an_x25519_or_x448_key_we_read_still_agrees(name):
    """RFC 8410's key agreement keys come back as the curve's name and the
    private bytes, and those bytes agree with python-cryptography: the
    shared secret with a third key is the same, and so is the public key.
    The bytes are written by python-cryptography in PKCS#8, PEM and DER,
    with and without the RFC 5958 public key."""
    from cryptography.hazmat.primitives.asymmetric import x25519, x448
    module = x25519 if name == "x25519" else x448
    exchange = allcrypt.x25519_exchange if name == "x25519" else allcrypt.x448_exchange
    public_key = allcrypt.x25519_public_key if name == "x25519" else allcrypt.x448_public_key
    generate = module.X25519PrivateKey.generate if name == "x25519" else \
        module.X448PrivateKey.generate
    for _ in range(4):
        key = generate()
        peer = generate()
        raw_public = key.public_key().public_bytes(serialization.Encoding.Raw,
                                                    serialization.PublicFormat.Raw)
        for encoding in (serialization.Encoding.PEM, serialization.Encoding.DER):
            data = key.private_bytes(encoding, serialization.PrivateFormat.PKCS8,
                                     serialization.NoEncryption())
            curve, private = allcrypt.private_key(data)
            assert curve == name
            assert private == key.private_bytes(serialization.Encoding.Raw,
                                                serialization.PrivateFormat.Raw,
                                                serialization.NoEncryption())
            assert public_key(private) == raw_public
            theirs = peer.exchange(key.public_key())
            assert exchange(private, peer.public_key().public_bytes(
                serialization.Encoding.Raw, serialization.PublicFormat.Raw)) == theirs


def test_a_short_scalar_is_padded_to_the_curve():
    """RFC 5915 section 3 fixes the OCTET STRING at the curve's width,
    but files with a shorter one exist and a signature needs the padded
    form. Generated keys almost never have a leading zero - one in 256 -
    so this makes one by stripping the zero out of a real key.
    """
    while True:
        key = ec.generate_private_key(ec.SECP256R1())
        value = key.private_numbers().private_value
        if value < (1 << 248):        # a genuine leading zero byte
            break
        # Not a loop that runs forever in practice, but not one to wait
        # on either: 255/256 of keys are rejected, so make one instead.
        blob = bytearray(key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING))
        full = value.to_bytes(32, "big")
        at = bytes(blob).find(full)
        assert at > 0
        blob[at] = 0x00               # force the top byte to zero
        value = int.from_bytes(bytes(blob[at:at + 32]), "big")
        short = value.to_bytes(31, "big")
        # Rewrite the OCTET STRING one byte shorter.
        rebuilt = bytes(blob[:at - 1]) + bytes([31]) + short + bytes(blob[at + 32:])
        # And fix the SEQUENCE length.
        rebuilt = bytes([rebuilt[0]]) + bytes([rebuilt[1] - 1]) + rebuilt[2:]
        ours = allcrypt.private_key(rebuilt)
        assert len(ours.private_bytes()) == 32, "the scalar was not padded"
        assert ours.private_bytes() == value.to_bytes(32, "big")
        return
    ours = allcrypt.private_key(key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING))
    assert len(ours.private_bytes()) == 32


def test_a_scalar_wider_than_the_curve_is_refused():
    """Not this curve's key, whatever else it is.

    Padding logic that trusted the length would underflow computing
    `width - len`, which in release is a very large allocation rather
    than an error.
    """
    key = ec.generate_private_key(ec.SECP256R1())
    blob = bytearray(key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING))
    value = key.private_numbers().private_value.to_bytes(32, "big")
    at = bytes(blob).find(value)
    assert at > 0
    # Forty bytes where thirty-two belong, and the two lengths fixed up.
    rebuilt = (bytes(blob[:at - 1]) + bytes([40]) + bytes(8) + value
               + bytes(blob[at + 32:]))
    rebuilt = bytes([rebuilt[0], rebuilt[1] + 8]) + rebuilt[2:]
    with pytest.raises(ValueError) as failure:
        allcrypt.private_key(rebuilt)
    assert "P-256" in str(failure.value)


def test_a_key_naming_two_different_curves_is_refused():
    """RFC 5915 section 3 says the inner parameters must be omitted
    inside PKCS#8. A file with both and a disagreement is malformed, and
    picking one is guessing which half the writer meant - so it is an
    error that says what the two answers were."""
    key = ec.generate_private_key(ec.SECP256R1())
    sec1 = key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING)   # has [0] params
    # Wrap that whole SEC1 key in a PKCS#8 whose algorithm identifier
    # says P-384 instead.
    p384 = bytes.fromhex("06052b81040022")                  # 1.3.132.0.34
    ec_oid = bytes.fromhex("06072a8648ce3d0201")            # 1.2.840.10045.2.1
    algorithm = _sequence(ec_oid + p384)
    inner = _octet_string(sec1)
    pkcs8 = _sequence(bytes([0x02, 0x01, 0x00]) + algorithm + inner)
    with pytest.raises(ValueError) as failure:
        allcrypt.private_key(pkcs8)
    assert "P-384" in str(failure.value) and "P-256" in str(failure.value)


def test_a_multi_prime_rsa_key_is_refused():
    """`prime1` and `prime2` of a three-prime key are a perfectly
    well-formed pair that computes the wrong thing, so the version has
    to be checked rather than assumed. Nothing generates one of these -
    `cryptography` will not - so the version byte is edited in a real
    two-prime key."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=1024)
    blob = bytearray(key.private_bytes(DER, SEC1_OR_PKCS1, NOTHING))
    version = _der_parts(bytes(blob))[0]
    tag, header, start, contents = version
    assert tag == 0x02 and contents == b"\x00"
    blob[start] = 0x01                          # "multi" (RFC 8017 A.1.2)
    with pytest.raises(ValueError) as failure:
        allcrypt.private_key(bytes(blob))
    assert "multi-prime" in str(failure.value)


def _sequence(contents):
    return bytes([0x30]) + _length(len(contents)) + contents


def _octet_string(contents):
    return bytes([0x04]) + _length(len(contents)) + contents


def _length(size):
    if size < 0x80:
        return bytes([size])
    body = size.to_bytes((size.bit_length() + 7) // 8, "big")
    return bytes([0x80 | len(body)]) + body


# ------------------------------------------------------- what it refuses ---

def test_an_encrypted_key_is_refused_by_name():
    """Because the remedy is a passphrase, not a different file.

    A reader told only "unsupported" goes looking for the wrong thing.
    """
    key = ec.generate_private_key(ec.SECP256R1())
    blob = key.private_bytes(
        PEM, PKCS8, serialization.BestAvailableEncryption(b"hunter2"))
    with pytest.raises(ValueError) as failure:
        allcrypt.private_key(blob)
    assert "encrypted" in str(failure.value).lower()


def test_a_public_key_is_not_a_private_key():
    key = ec.generate_private_key(ec.SECP256R1())
    blob = key.public_key().public_bytes(
        PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    with pytest.raises(ValueError):
        allcrypt.private_key(blob)


def test_a_certificate_and_key_in_one_file_finds_the_key():
    """The normal deployment shape - what `load_cert_chain` is handed."""
    import datetime
    from cryptography import x509
    from cryptography.x509.oid import NameOID

    key = ec.generate_private_key(ec.SECP256R1())
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "localhost")])
    now = datetime.datetime.now(datetime.timezone.utc)
    certificate = (x509.CertificateBuilder()
                   .subject_name(name).issuer_name(name)
                   .public_key(key.public_key()).serial_number(1)
                   .not_valid_before(now - datetime.timedelta(days=1))
                   .not_valid_after(now + datetime.timedelta(days=1))
                   .sign(key, hashes.SHA256()))
    combined = (certificate.public_bytes(PEM)
                + key.private_bytes(PEM, PKCS8, NOTHING))
    ours = allcrypt.private_key(combined)
    assert ours.private_bytes() == \
        key.private_numbers().private_value.to_bytes(32, "big")


def test_a_curve_we_cannot_compute_on_is_refused_by_name():
    """A private key on an unknown curve is nothing at all - unlike a
    *public* key in a certificate, which is still a link in a chain and
    is kept as `UnsupportedCurve`."""
    key = ec.generate_private_key(ec.BrainpoolP256R1())   # not implemented here
    with pytest.raises(ValueError) as failure:
        allcrypt.private_key(key.private_bytes(PEM, PKCS8, NOTHING))
    assert "1.3.36.3.3.2.8.1.1.7" in str(failure.value)


def test_garbage_is_an_error_and_never_a_panic():
    key = ec.generate_private_key(ec.SECP256R1())
    der = key.private_bytes(DER, PKCS8, NOTHING)
    for cut in range(1, len(der)):
        with pytest.raises(ValueError):
            allcrypt.private_key(der[:cut])
    for flip in range(0, len(der), 7):
        broken = bytearray(der)
        broken[flip] ^= 0xff
        try:
            allcrypt.private_key(bytes(broken))
        except ValueError:
            pass


# --------------------------------------------------------- encrypted keys ---
#
# The Rust suite (`tests/test_encrypted_keys.rs`) checks the fixtures in
# `tests/keys/`, which are pinned because the OpenSSL that produced them
# is already losing the ability to. These check the *Python* surface and
# the one thing the Rust side cannot: agreement with python-cryptography
# on the keys it will still read.

ENCRYPTED_KEYS = pathlib.Path(__file__).resolve().parent.parent / "tests" / "keys"


def _fixture(name):
    return (ENCRYPTED_KEYS / name).read_bytes()


@pytest.mark.parametrize("name", [
    "rsa_pbes2_aes128.pem", "rsa_pbes2_aes192.pem", "rsa_pbes2_aes256.pem",
    "rsa_pbes2_3des.pem", "rsa_pbes2_des.pem", "rsa_pbes2_rc2.pem",
    "rsa_pbes2_aes256_prf_sha1.pem", "rsa_pbes2_aes256_prf_sha256.pem",
    "rsa_pbes2_aes256_prf_sha512.pem",
    "rsa_pbes1_md5_des.pem", "rsa_pbes1_md5_rc2.pem", "rsa_pbes1_sha1_des.pem",
    "rsa_pkcs12_sha1_3des.pem", "rsa_pkcs12_sha1_rc2_40.pem",
    "rsa_pkcs12_sha1_rc4_128.pem",
])
def test_an_encrypted_rsa_key_reaches_python(name):
    """Every scheme, through the binding, giving back the same modulus."""
    want = allcrypt.private_key(_fixture("rsa_plain.pem"))
    got = allcrypt.private_key(_fixture(name), b"secret")
    assert got.numbers["n"] == want.numbers["n"], name
    assert got.numbers["p"] == want.numbers["p"], name


@pytest.mark.parametrize("name", ["ec_pbes2_aes256.pem", "ec_pkcs12_sha1_3des.pem"])
def test_an_encrypted_ec_key_reaches_python(name):
    want = allcrypt.private_key(_fixture("ec_plain.pem"))
    got = allcrypt.private_key(_fixture(name), b"secret")
    assert got.private_bytes() == want.private_bytes(), name
    assert got.curve == want.curve, name


def test_a_wrong_password_raises_rather_than_returning_a_key():
    """None of these schemes is authenticated, so a wrong password
    decrypts to random bytes. If that came back as a key, every test
    above would pass against an implementation that ignored the
    password."""
    with pytest.raises(ValueError):
        allcrypt.private_key(_fixture("rsa_pbes2_aes256.pem"), b"wrong")


def test_an_encrypted_key_with_no_password_names_the_remedy():
    with pytest.raises(ValueError) as caught:
        allcrypt.private_key(_fixture("rsa_pbes2_aes256.pem"))
    assert "encrypted" in str(caught.value)


def test_a_password_on_an_unencrypted_key_is_ignored():
    """A caller that always has a passphrase should not have to know
    which of its files used one."""
    with_password = allcrypt.private_key(_fixture("rsa_plain.pem"), b"unused")
    without = allcrypt.private_key(_fixture("rsa_plain.pem"))
    assert with_password.numbers["n"] == without.numbers["n"]


@pytest.mark.parametrize("name", [
    "rsa_pbes2_aes128.pem", "rsa_pbes2_aes256.pem", "rsa_pbes2_3des.pem",
    "rsa_pbes2_aes256_prf_sha256.pem", "rsa_pbes2_aes256_prf_sha512.pem",
    "rsa_pkcs12_sha1_3des.pem", "rsa_pkcs12_sha1_rc2_40.pem",
    "rsa_pkcs12_sha1_rc4_128.pem", "rsa_pbes1_md5_des.pem",
])
def test_the_decrypted_key_agrees_with_python_cryptography(name):
    """Differential, for the schemes cryptography will still read.

    Not all of them: `pbeWithSHA1AndDES-CBC` and `pbeWithMD5AndRC2-CBC`
    are refused there with "Unknown key encryption algorithm", and
    `-v2 des-cbc` and `-v2 rc2-cbc` need OpenSSL's legacy provider. Those
    rows are checked against the pinned plaintext in the Rust suite
    instead, which is the weaker form of evidence and the only one
    available - and the reason the fixtures are pinned at all.
    """
    from cryptography.hazmat.primitives.serialization import load_pem_private_key
    theirs = load_pem_private_key(_fixture(name), b"secret")
    ours = allcrypt.private_key(_fixture(name), b"secret")
    # `numbers` gives big-endian bytes; cryptography gives ints.
    as_int = lambda b: int.from_bytes(b, "big")
    assert as_int(ours.numbers["n"]) == theirs.private_numbers().public_numbers.n, name
    assert as_int(ours.numbers["p"]) == theirs.private_numbers().p, name
    assert as_int(ours.numbers["q"]) == theirs.private_numbers().q, name


def test_the_schemes_this_machine_can_no_longer_produce_are_still_read():
    """The point of the whole exercise, stated as a test.

    These four fixtures cannot be regenerated on this machine without
    `-provider legacy`, and two of them cannot be read by
    python-cryptography at all. They are checked in, and they open.
    """
    want = allcrypt.private_key(_fixture("rsa_plain.pem")).numbers["n"]
    for name in ["rsa_pbes1_sha1_des.pem", "rsa_pbes1_md5_rc2.pem",
                 "rsa_pbes2_des.pem", "rsa_pbes2_rc2.pem"]:
        assert allcrypt.private_key(_fixture(name), b"secret").numbers["n"] == want, name


# ------------------------------------------------------- encrypting keys ---

def _pem_der(pem):
    import base64
    lines = pem.decode().strip().splitlines()
    return base64.b64decode("".join(lines[1:-1]))


@pytest.mark.parametrize("name", [
    "rsa_pbes2_aes128.pem", "rsa_pbes2_aes256.pem", "rsa_pbes2_3des.pem",
    "rsa_pbes2_des.pem", "rsa_pbes2_rc2.pem", "rsa_pbes2_aes256_prf_sha1.pem",
    "rsa_pbes2_aes256_prf_sha512.pem", "rsa_pbes1_md5_des.pem", "rsa_pbes1_md5_rc2.pem",
    "rsa_pkcs12_sha1_3des.pem", "rsa_pkcs12_sha1_rc2_40.pem", "rsa_pkcs12_sha1_rc4_128.pem",
])
def test_encrypting_with_a_files_parameters_reproduces_it(name):
    """Given an OpenSSL file's salt, count and IV, the plain key encrypts
    to that file again, byte for byte."""
    p = allcrypt.private_key_encryption(_fixture(name))
    again = allcrypt.encrypt_private_key(
        _fixture("rsa_plain.pem"), b"secret", p["scheme"], prf=p["prf"],
        iterations=p["iterations"], salt=p["salt"], iv=p["iv"] or None)
    assert again == _pem_der(_fixture(name)), (name, p["scheme"])


@pytest.mark.parametrize("scheme", ["aes-128-cbc", "aes-256-cbc", "des-ede3-cbc",
                                    "pbe-sha1-3des", "pbe-sha1-rc2-40", "pbe-sha1-rc4-128",
                                    "pbe-md5-des"])
def test_python_cryptography_reads_what_is_written(scheme):
    from cryptography.hazmat.primitives.serialization import load_der_private_key
    plain = _fixture("ec_plain.pem")
    sealed = allcrypt.encrypt_private_key(plain, b"pw", scheme, iterations=10)
    theirs = load_der_private_key(sealed, b"pw")
    ours = allcrypt.private_key(plain)
    assert theirs.private_numbers().private_value == int.from_bytes(ours.private_bytes(), "big")


def test_every_scheme_round_trips_through_private_key():
    want = allcrypt.private_key(_fixture("rsa_plain.pem")).numbers["n"]
    schemes = allcrypt.encryption_schemes()
    assert "aes-256-cbc" in schemes and "pbe-md2-des" in schemes
    for scheme in schemes:
        sealed = allcrypt.encrypt_private_key(_fixture("rsa_plain.pem"), "pä".encode(), scheme,
                                              iterations=2, pem=True)
        assert sealed.startswith(b"-----BEGIN ENCRYPTED PRIVATE KEY-----")
        assert allcrypt.private_key_encryption(sealed)["scheme"] == scheme
        assert allcrypt.private_key(sealed, "pä".encode()).numbers["n"] == want, scheme


def test_the_defaults():
    p = allcrypt.private_key_encryption(
        allcrypt.encrypt_private_key(_fixture("ec_plain.pem"), b"pw", iterations=1))
    assert (p["scheme"], p["prf"], len(p["salt"]), len(p["iv"])) == \
        ("aes-256-cbc", "sha256", 16, 16)
    p = allcrypt.private_key_encryption(
        allcrypt.encrypt_private_key(_fixture("ec_plain.pem"), b"pw", "pbe-sha1-3des"))
    assert (p["prf"], p["iterations"], len(p["salt"]), p["iv"]) == (None, 2048, 8, b"")


def test_only_a_pkcs8_key_is_encrypted():
    sec1 = ec.generate_private_key(ec.SECP256R1()).private_bytes(
        serialization.Encoding.DER, serialization.PrivateFormat.TraditionalOpenSSL,
        serialization.NoEncryption())
    with pytest.raises(ValueError, match="PKCS#8"):
        allcrypt.encrypt_private_key(sec1, b"pw", iterations=1)
    with pytest.raises(ValueError):
        allcrypt.encrypt_private_key(_fixture("ec_plain.pem"), b"pw", "aes-256-ctr")
