"""crypt(3) through the Python surface, against vectors/unix_crypt.vec:
libxcrypt's known answers (generated by Passlib) that the system libcrypt
reproduced, recorded by scripts/make_unix_crypt_vectors.py. Offline."""

import os

import pytest

import allcrypt

VECTORS = os.path.join(os.path.dirname(__file__), "..", "vectors", "unix_crypt.vec")


def decode_c(s):
    """A C string literal's bytes: \\xHH, octal and one-character escapes."""
    out = bytearray()
    i = 0
    while i < len(s):
        if s[i] != "\\":
            out.append(ord(s[i]))
            i += 1
        elif s[i + 1] == "x":
            out.append(int(s[i + 2:i + 4], 16))
            i += 4
        elif s[i + 1] in "01234567":
            j = i + 1
            while j < len(s) and j < i + 4 and s[j] in "01234567":
                j += 1
            out.append(int(s[i + 1:j], 8) & 0xFF)
            i = j
        else:
            out.append({"n": 10, "t": 9, "r": 13}.get(s[i + 1], ord(s[i + 1])))
            i += 2
    return bytes(out)


def rows():
    out = []
    with open(VECTORS) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            method, *words = line.split()
            fields = dict(w.split("=", 1) for w in words)
            out.append((method, decode_c(fields["setting"]).decode(),
                        b"" if fields["phrase"] == "-" else bytes.fromhex(fields["phrase"]),
                        decode_c(fields["expected"]).decode()))
    assert len(out) > 3000
    return out


ROWS = rows()


def test_every_row_through_unix_crypt_and_verify():
    for method, setting, phrase, expected in ROWS:
        assert allcrypt.unix_crypt(phrase, setting) == expected, (method, setting)
        assert allcrypt.unix_crypt_verify(phrase, expected), (method, setting)


def test_helpers_rebuild_the_rows_from_their_parameters():
    seen = {}
    for method, setting, phrase, expected in ROWS:
        got = None
        if method == "descrypt":
            got = allcrypt.unix_crypt_des(phrase, salt=setting)
        elif method == "md5crypt" and len(setting) <= 11:
            got = allcrypt.unix_crypt_md5(phrase, salt=setting[3:])
        elif method in ("sha256crypt", "sha512crypt") and "rounds=" not in setting \
                and len(setting) <= 19:
            fn = allcrypt.unix_crypt_sha256 if method == "sha256crypt" else allcrypt.unix_crypt_sha512
            got = fn(phrase, salt=setting[3:])
        elif method == "nt":
            got = allcrypt.unix_crypt_nt(phrase)
        if got is not None:
            assert got == expected, (method, setting)
            seen[method] = seen.get(method, 0) + 1
    assert set(seen) == {"descrypt", "md5crypt", "sha256crypt", "sha512crypt", "nt"}, seen


@pytest.mark.parametrize("make", [
    lambda: allcrypt.unix_crypt_des(b"hunter2"),
    lambda: allcrypt.unix_crypt_bigcrypt(b"hunter2"),
    lambda: allcrypt.unix_crypt_bsdi(b"hunter2", 725),
    lambda: allcrypt.unix_crypt_md5(b"hunter2"),
    lambda: allcrypt.unix_crypt_sha256(b"hunter2", rounds=1000),
    lambda: allcrypt.unix_crypt_sha512(b"hunter2"),
    lambda: allcrypt.unix_crypt_bcrypt(b"hunter2", 4),
    lambda: allcrypt.unix_crypt_sha1(b"hunter2", 10),
    lambda: allcrypt.unix_crypt_sun_md5(b"hunter2", extra_rounds=5),
    lambda: allcrypt.unix_crypt_nt(b"hunter2"),
])
def test_a_fresh_salt_verifies(make):
    stored = make()
    assert allcrypt.unix_crypt_verify(b"hunter2", stored)
    assert not allcrypt.unix_crypt_verify(b"hunter3", stored)


@pytest.mark.parametrize("call", [
    lambda: allcrypt.unix_crypt_des(b"pw", salt="a"),
    lambda: allcrypt.unix_crypt_bsdi(b"pw", 0),
    lambda: allcrypt.unix_crypt_md5(b"pw", salt="nine chars"),
    lambda: allcrypt.unix_crypt_sha512(b"pw", rounds=999),
    lambda: allcrypt.unix_crypt_sha256(b"pw", salt="has$dollar"),
    lambda: allcrypt.unix_crypt_bcrypt(b"pw", 3),
    lambda: allcrypt.unix_crypt_bcrypt(b"pw", 4, salt=bytes(15)),
    lambda: allcrypt.unix_crypt_bcrypt(b"pw", 4, variant="2c"),
    lambda: allcrypt.unix_crypt_sha1(b"pw", 0),
    lambda: allcrypt.unix_crypt_sun_md5(b"pw", salt=""),
    lambda: allcrypt.unix_crypt(b"pw", "$2b$05$short"),
])
def test_bad_parameters_raise_value_error(call):
    with pytest.raises(ValueError):
        call()
